### ISSUE TITLE
Inactive player data release

### ISSUE THREAD

**Issue by Nikusama** [harbingerofme/R2DS-Essentials#5]
After the player exits, the server quota will still be occupied. Can you integrate and release the player's function in mod?

**Comment by xiaoxiao921** [comment]
I've talked to the dev about this. We'll see if we do our own fix in the meantime

**Comment by xiaoxiao921** [comment]
Fixed in e8da209cbe0ec712e7d5ad7e5a8baed63899d30f until the dev patch it themselves
